spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    producer:
      bootstrap-servers: 3.35.218.206:9092,3.34.3.106:9092,52.79.236.102:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap.servers: 3.35.218.206:9092,3.34.3.106:9092,52.79.236.102:9092
    template:
      default-topic: library-events
---
spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring:
  profiles: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
